const STORE = 'keyledger-v1';
const seedAssignments = [
  ['Amoor','eace8434ca4ed7f491a9b158b7a34c74','1 An Pro','27/02/2026 18:35','27/02/2027 18:35'],
  ['Faze','9c8baeec88e28d935a9de53cfb6d1004','Lifetime','05/03/2026 18:54',''],
  ['Matou','282ee6db86f62954a52c755762fd6cb4','Lifetime','05/03/2026 18:59',''],
  ['keno971','ec1892fc18bc5c30a63566c1979ad04f','1 An Pro','11/04/2026 23:55','11/04/2027 23:55'],
  ['Tommy egan','9c8baeec88e28d935a9de53cfb6d1004','Lifetime','10/05/2026 21:07',''],
  ['mowgli','7f0eee8547a4edfcb37f7c4e8f40342b','1 An Pro','06/06/2026 15:46','06/06/2027 15:46'],
  ['quent42','43c1f7ff576a75d95a8f2258279057ea','1 An Pro','09/06/2026 16:38','09/06/2027 16:38'],
  ['tazz','7f0eee8547a4edfcb37f7c4e8f40342b','Lifetime','15/06/2026 21:54',''],
  ['fury','09edcfe49722d402003fe47af2bf7fad','1 Mois Pro','20/06/2026 14:52','20/07/2026 14:52']
].map(([pseudo,key,type,assignedAt,endsAt])=>({id:uid(),pseudo,key,type,assignedAt:parseOldDate(assignedAt),endsAt:parseOldDate(endsAt),status:'active',discordId:'',email:'',notes:'Importé depuis l’ancien tableau Lovable.'}));

const seedInventoryKeys = ['282ee6db86f62954a52c755762fd6cb4','47bdec833c0c8dc9b1620f38fdd6aa11','ea5156290c3f4332caad24f32e38c72a','eace8434ca4ed7f491a9b158b7a34c74','34b63f2e5f1cf87ea7dd3032551eb36c','ccfeb5c4a94d78c08629c85bc25bd356','71434e3c4892c45a6b5e05afc442eb8c','bbd035910dbd3649f52b390cfea2ea28','43c1f7ff576a75d95a8f2258279057ea','ec1892fc18bc5c30a63566c1979ad04f','09edcfe49722d402003fe47af2bf7fad','c36b353808e4330062d66771835032d7','45f261531295dcdcfd3d49e9f1080ad4','43250f10be6a2065f7ff5c2a242a2632','85d85d81e88564116bb504c0ab12a990','63a2e6381c5727ecde28bdc7a72e41f2','d6f7447d7e643c869f2f5acdc5c461c9','5f404451b9f26f58666374dceb2aa1a3','9c8baeec88e28d935a9de53cfb6d1004','715019f35f55ccb2a17de98cbbe18976','7f0eee8547a4edfcb37f7c4e8f40342b'];
const seedTypeByKey = {"282ee6db86f62954a52c755762fd6cb4":"Lifetime","47bdec833c0c8dc9b1620f38fdd6aa11":"Lifetime","ea5156290c3f4332caad24f32e38c72a":"Lifetime","eace8434ca4ed7f491a9b158b7a34c74":"Lifetime","34b63f2e5f1cf87ea7dd3032551eb36c":"Lifetime","ccfeb5c4a94d78c08629c85bc25bd356":"Lifetime","71434e3c4892c45a6b5e05afc442eb8c":"Lifetime","bbd035910dbd3649f52b390cfea2ea28":"Lifetime","43c1f7ff576a75d95a8f2258279057ea":"1 An Pro","ec1892fc18bc5c30a63566c1979ad04f":"1 An Pro","09edcfe49722d402003fe47af2bf7fad":"1 An Pro","c36b353808e4330062d66771835032d7":"1 An Pro","45f261531295dcdcfd3d49e9f1080ad4":"1 An Pro","43250f10be6a2065f7ff5c2a242a2632":"1 An Pro","85d85d81e88564116bb504c0ab12a990":"1 An Pro","63a2e6381c5727ecde28bdc7a72e41f2":"1 An Pro","d6f7447d7e643c869f2f5acdc5c461c9":"1 An Pro","5f404451b9f26f58666374dceb2aa1a3":"1 Mois Lite","9c8baeec88e28d935a9de53cfb6d1004":"Lifetime","715019f35f55ccb2a17de98cbbe18976":"1 Mois Pro","7f0eee8547a4edfcb37f7c4e8f40342b":"Lifetime"};
function makeSeedStock(){return [...seedInventoryKeys.map(key=>{const assignment=seedAssignments.find(a=>a.key===key);return {id:uid(),key,type:seedTypeByKey[key],sourceDate:'Ancien inventaire Lovable',importedAt:new Date().toISOString(),state:assignment?'assigned':'available'}}),{id:uid(),key:'Entrée d’inventaire à vérifier',type:'Lifetime',sourceDate:'Ancien inventaire Lovable',importedAt:new Date().toISOString(),state:'review',note:'Une des 22 lignes de l’ancien stock ne contient pas une clé valide.'}]}

let db = load(); let currentView = 'dashboard'; let toastTimer;
let cloud = { configured:false, client:null, session:null };
const $ = (s) => document.querySelector(s);
function uid(){return crypto.randomUUID?.() || `${Date.now()}-${Math.random().toString(16).slice(2)}`}
function load(){try{const saved=JSON.parse(localStorage.getItem(STORE));if(saved?.stock&&saved?.assignments){const active=new Set(saved.assignments.filter(a=>a.status==='active'||a.status==='paused').map(a=>a.key));const known=new Map(saved.stock.map(k=>[k.key,k]));for(const seed of makeSeedStock()){const current=known.get(seed.key);if(!current){saved.stock.push(seed);known.set(seed.key,seed)}else if(current.sourceDate==='Ancien inventaire Lovable'){current.type=seed.type}}saved.stock.forEach(k=>{if(!k.state)k.state=active.has(k.key)?'assigned':'available';if(active.has(k.key)&&k.state==='available')k.state='assigned'});return {...saved,version:2}}}catch{}return {version:2,stock:makeSeedStock(),assignments:seedAssignments,archive:[]}}
function save(){if(!cloud.session)localStorage.setItem(STORE,JSON.stringify(db));render()}
function normal(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim()}
function canonicalType(value){const type=normal(value);if(type.includes('lifetime'))return 'Lifetime';if(type.includes('annual')||type.includes('annuel')||type.includes('an pro'))return '1 An Pro';if(type.includes('monthly')||type.includes('mensuel')||type.includes('mois')||type.includes('month'))return '1 Mois';return value||''}
function parseOldDate(v){if(!v)return '';const m=String(v).match(/(\d{2})\/(\d{2})\/(\d{4})\s+(\d{2}):(\d{2})/);return m?`${m[3]}-${m[2]}-${m[1]}T${m[4]}:${m[5]}`:''}
function dateLabel(v){if(!v)return 'Sans échéance';const d=new Date(v);return Number.isNaN(+d)?v:new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium',timeStyle:'short'}).format(d)}
function dateShort(v){if(!v)return '—';const d=new Date(v);return Number.isNaN(+d)?v:new Intl.DateTimeFormat('fr-FR',{dateStyle:'short'}).format(d)}
function escapeHtml(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
function activeAssignments(){return db.assignments.filter(a=>a.status==='active'||a.status==='paused')}
function historyAssignments(){return [...db.assignments,...db.archive]}
function availableStock(){return db.stock.filter(k=>k.state==='available')}
function assignmentsForKey(key){return activeAssignments().filter(a=>a.key===key)}
function inventoryStatus(k){if(k.state==='review')return {label:'À vérifier',className:'paused',people:'—'};const people=assignmentsForKey(k.key).map(a=>a.pseudo);return people.length?{label:'Attribuée',className:'due',people:people.join(', ')}:{label:'Disponible',className:'',people:'—'}}
function dueState(a){if(a.status==='paused')return 'paused';if(!a.endsAt)return '';const days=(new Date(a.endsAt)-Date.now())/86400000;return days<0?'overdue':days<=7?'due':''}
function dueText(a){if(!a.endsAt)return 'Sans échéance';const d=Math.ceil((new Date(a.endsAt)-Date.now())/86400000);return d<0?`Échue depuis ${Math.abs(d)} j`:d===0?'Échéance aujourd’hui':`${d} j restant${d>1?'s':''}`}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3300)}
function toLocalInput(value){if(!value)return '';const date=new Date(value);if(Number.isNaN(+date))return value.slice(0,16);return new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16)}
function updateConnectionButton(){const button=$('#connection-button');if(!cloud.configured){button.textContent='Mode local';button.disabled=true;return}button.disabled=false;button.textContent=cloud.session?'Connecté · Synchronisé':'Connexion'}
async function api(path, options={}){const token=cloud.session?.access_token;if(!token)throw new Error('Connecte-toi d’abord.');const response=await fetch(`/.netlify/functions/ledger${path}`,{...options,headers:{'content-type':'application/json',authorization:`Bearer ${token}`,...options.headers}});const body=await response.json();if(!response.ok)throw new Error(body.error||'Erreur serveur');return body}
async function refreshCloud(){const data=await api('');const mapAssignment=(assignment)=>({id:assignment.id,pseudo:assignment.discord_name,key:assignment.inventory_keys?.key_value||'',type:canonicalType(assignment.inventory_keys?.license_type||''),assignedAt:toLocalInput(assignment.assigned_at),endsAt:toLocalInput(assignment.ends_at),status:assignment.status==='archived'?'archived':assignment.status,discordId:assignment.discord_id||'',email:assignment.email||'',notes:assignment.notes||'',archivedAt:toLocalInput(assignment.archived_at)});db={version:2,stock:data.inventory.map(key=>({id:key.id,key:key.key_value,type:canonicalType(key.license_type),sourceDate:key.source_date,state:key.state,note:key.note||'',importedAt:key.created_at})),assignments:data.assignments.filter(a=>a.status!=='archived').map(mapAssignment),archive:data.assignments.filter(a=>a.status==='archived').map(mapAssignment)};render()}
async function initCloud(){try{if(location.protocol==='file:')return;const response=await fetch('/.netlify/functions/public-config');const config=await response.json();if(!config.configured||!window.supabase)return;cloud.configured=true;cloud.client=window.supabase.createClient(config.url,config.anonKey);const {data:{session}}=await cloud.client.auth.getSession();cloud.session=session;if(session)await refreshCloud()}catch(error){console.warn('KeyLedger cloud mode unavailable',error)}finally{updateConnectionButton()}}
function setView(view){currentView=view;document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));document.querySelectorAll('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#page-title').textContent={dashboard:'Vue d’ensemble',stock:'Inventaire des clés',assignments:'Attributions',history:'Historique',data:'Import & sauvegarde'}[view];window.scrollTo({top:0,behavior:'smooth'})}
function render(){const active=activeAssignments();const due=active.filter(a=>['due','overdue'].includes(dueState(a)));$('#stock-nav-count').textContent=db.stock.length;$('#assignment-nav-count').textContent=active.length;$('#history-nav-count').textContent=historyAssignments().length;$('#stat-stock').textContent=availableStock().length;$('#stat-active').textContent=active.length;$('#stat-due').textContent=due.length;$('#stat-archive').textContent=db.archive.length;renderDue(due);renderBreakdown();renderStock();renderAssignments();renderHistory()}
function renderDue(due){const list=$('#due-list');if(!due.length){list.innerHTML='<p class="muted">Aucune échéance dans les 7 prochains jours.</p>';return}list.innerHTML=due.sort((a,b)=>new Date(a.endsAt)-new Date(b.endsAt)).slice(0,7).map(a=>`<div class="compact-row"><div><b>${escapeHtml(a.pseudo)}</b><small>${escapeHtml(a.type)} · ${escapeHtml(dateLabel(a.endsAt))}</small></div><span class="pill ${dueState(a)}">${dueText(a)}</span></div>`).join('')}
function renderBreakdown(){const box=$('#type-breakdown');const groups=availableStock().reduce((m,k)=>{m[k.type||'Sans type']=(m[k.type||'Sans type']||0)+1;return m},{});const max=Math.max(1,...Object.values(groups));box.innerHTML=Object.keys(groups).length?Object.entries(groups).sort((a,b)=>b[1]-a[1]).map(([type,n])=>`<div class="breakdown-row"><span>${escapeHtml(type)}</span><div class="bar"><i style="width:${n/max*100}%"></i></div><b>${n}</b></div>`).join(''):'<p class="muted">Le détail apparaîtra après l’import du stock.</p>'}
function renderStock(){const q=normal($('#stock-search').value);const items=db.stock.filter(k=>!q||normal(`${k.key} ${k.type} ${k.sourceDate} ${k.note}`).includes(q));$('#stock-subtitle').textContent=`${db.stock.length} entrée(s) d’inventaire · ${availableStock().length} clé(s) disponible(s).`;$('#stock-table').innerHTML=items.length?items.map(k=>{const status=inventoryStatus(k);return `<tr><td class="key">${escapeHtml(k.key)}</td><td>${escapeHtml(k.type||'—')}</td><td class="subtle">${escapeHtml(k.sourceDate||'—')}</td><td><span class="pill ${status.className}">${status.label}</span></td><td title="${escapeHtml(status.people)}">${escapeHtml(status.people)}</td><td><div class="row-actions">${k.state==='available'?`<button class="small-button" data-assign="${k.id}">Attribuer</button>`:''}${k.state==='review'?`<button class="small-button" data-release-key="${k.id}">Rendre disponible</button>`:''}<button class="small-button" data-note-key="${k.id}">${k.note?'Note ✓':'Note'}</button></div></td></tr>`}).join(''):'<tr><td class="empty" colspan="6">Aucune clé trouvée.</td></tr>'}
function renderAssignments(){const q=normal($('#assignment-search').value);const items=activeAssignments().filter(a=>!q||normal(`${a.pseudo} ${a.email} ${a.discordId} ${a.key} ${a.type}`).includes(q));$('#assignment-table').innerHTML=items.length?items.sort((a,b)=>(a.endsAt||'9999').localeCompare(b.endsAt||'9999')).map(a=>{const state=dueState(a),label=state==='overdue'?'Échue':state==='due'?dueText(a):a.status==='paused'?'En pause':'Active';return `<tr><td><b>${escapeHtml(a.pseudo)}</b>${a.email?`<small class="subtle">${escapeHtml(a.email)}</small>`:''}</td><td class="key">${escapeHtml(a.key)}</td><td>${escapeHtml(a.type||'—')}</td><td class="subtle">${dateShort(a.assignedAt)}</td><td>${a.endsAt?dateShort(a.endsAt):'—'}</td><td><span class="pill ${state}">${label}</span></td><td><div class="row-actions"><button class="small-button" data-edit="${a.id}">Modifier</button><button class="small-button danger" data-archive="${a.id}">Terminer</button></div></td></tr>`}).join(''):'<tr><td class="empty" colspan="7">Aucune attribution active.</td></tr>'}
function renderHistory(){const q=normal($('#history-search').value);const items=historyAssignments().filter(a=>!q||normal(`${a.pseudo} ${a.key} ${a.type} ${a.notes}`).includes(q));$('#history-table').innerHTML=items.length?items.sort((a,b)=>String(b.archivedAt||b.assignedAt).localeCompare(String(a.archivedAt||a.assignedAt))).map(a=>{const archived=Boolean(a.archivedAt);const state=archived?'Terminée':a.status==='paused'?'En pause':'Active';return `<tr><td>${escapeHtml(a.pseudo)}</td><td class="key">${escapeHtml(a.key)}</td><td>${escapeHtml(a.type||'—')}</td><td>${dateShort(a.assignedAt)}</td><td>${dateShort(a.endsAt)}</td><td><span class="pill ${archived?'paused':''}">${state}</span>${archived?`<small class="subtle">${dateShort(a.archivedAt)}</small>`:''}</td><td title="${escapeHtml(a.notes)}">${escapeHtml(a.notes||'—')}</td></tr>`}).join(''):'<tr><td class="empty" colspan="7">Aucune attribution dans l’historique.</td></tr>'}
function openAssignment(stockId='',editId=''){const dialog=$('#assignment-dialog'), editing=db.assignments.find(a=>a.id===editId), free=availableStock();const select=$('#assignment-stock-key');select.innerHTML=free.map(k=>`<option value="${k.id}">${k.key} · ${k.type||'Sans type'}</option>`).join('');$('#assignment-id').value=editId;$('#key-picker-wrap').hidden=Boolean(editing);$('#dialog-kicker').textContent=editing?'MODIFIER L’ATTRIBUTION':'NOUVELLE ATTRIBUTION';$('#dialog-title').textContent=editing?'Modifier l’attribution':'Attribuer une clé';if(editing){$('#assignment-key').value=editing.key;$('#client-pseudo').value=editing.pseudo;$('#discord-id').value=editing.discordId;$('#client-email').value=editing.email;$('#assignment-date').value=editing.assignedAt;$('#expiry-date').value=editing.endsAt;$('#assignment-status').value=editing.status;$('#assignment-notes').value=editing.notes;$('#key-preview').textContent=`${editing.key} · ${editing.type||'Sans type'}`}else{if(!free.length){toast('Aucune clé disponible dans l’inventaire.');setView('stock');return}select.value=stockId||free[0].id;$('#assignment-key').value='';$('#client-pseudo').value='';$('#discord-id').value='';$('#client-email').value='';$('#assignment-date').value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);$('#expiry-date').value='';$('#assignment-status').value='active';$('#assignment-notes').value='';updateKeyPreview()}dialog.showModal()}
function updateKeyPreview(){const k=availableStock().find(x=>x.id===$('#assignment-stock-key').value);$('#key-preview').textContent=k?`${k.key} · ${k.type||'Sans type'}`:''}
async function archive(id){const a=db.assignments.find(x=>x.id===id);if(!a)return;if(!confirm(`Archiver l’attribution de ${a.pseudo} ? La clé passera à « À vérifier » dans l’inventaire.`))return;if(cloud.session){try{await api('',{method:'PATCH',body:JSON.stringify({action:'finish',assignmentId:id})});await refreshCloud();toast('Attribution terminée et historique conservé.')}catch(error){toast(error.message)}return}db.assignments=db.assignments.filter(x=>x.id!==id);const item=db.stock.find(k=>k.key===a.key);if(item)item.state='review';db.archive.unshift({...a,archivedAt:new Date().toISOString()});save();toast('Attribution archivée : clé marquée « À vérifier ».')}
function openKeyNote(id){const key=db.stock.find(k=>k.id===id);if(!key)return;$('#note-key-id').value=id;$('#note-key-label').textContent=`${key.key} · ${key.type||'Sans type'}`;$('#key-note').value=key.note||'';$('#key-note-dialog').showModal()}
async function releaseKey(id){const key=db.stock.find(k=>k.id===id);if(!key)return;if(!confirm(`Rendre la clé « ${key.key} » disponible ? L’historique des attributions sera conservé.`))return;try{if(cloud.session){await api('',{method:'PATCH',body:JSON.stringify({action:'release-key',keyId:id,note:'Remise à disposition manuelle depuis KeyLedger.'})});await refreshCloud()}else{key.state='available';save()}toast('Clé rendue disponible ; historique conservé.')}catch(error){toast(error.message)}}
function parseCsv(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const sep=lines[0].includes(';')?';':',';const split=line=>line.split(sep).map(x=>x.trim().replace(/^"|"$/g,'').replace(/""/g,'"'));const head=split(lines.shift()).map(normal);const keyI=head.findIndex(x=>['cle','key','licence','license'].some(n=>x.includes(n))),typeI=head.findIndex(x=>x.includes('type')),dateI=head.findIndex(x=>x==='date'||x.includes('date'));if(keyI<0)throw new Error('Colonne « Clé » introuvable.');return lines.map(split).map(c=>({key:c[keyI]?.trim(),type:c[typeI]?.trim()||'',sourceDate:c[dateI]?.trim()||''})).filter(x=>x.key)}
async function importCsv(files){let added=0,skipped=0;const existing=new Set(db.stock.map(x=>x.key));const assigned=new Set(activeAssignments().map(x=>x.key));for(const file of files){const rows=parseCsv(await file.text());for(const row of rows){if(existing.has(row.key)){skipped++;continue}existing.add(row.key);db.stock.push({id:uid(),...row,importedAt:new Date().toISOString(),state:assigned.has(row.key)?'assigned':'available'});added++}}save();$('#import-report').textContent=`${added} clé(s) ajoutée(s), ${skipped} doublon(s) ignoré(e)(s).`;toast(`${added} clé(s) importée(s) dans l’inventaire.`)}
async function importHtml(file){const doc=new DOMParser().parseFromString(await file.text(),'text/html');const rows=[...doc.querySelectorAll('tbody tr')];let added=0,skipped=0;for(const row of rows){const cells=[...row.querySelectorAll('td')].map(c=>c.textContent.trim().replace(/\s+/g,' '));const key=cells.find(x=>/^[a-f0-9]{32}$/i.test(x));if(!key||db.assignments.some(a=>a.key===key&&a.pseudo===cells[0])){skipped++;continue}db.assignments.push({id:uid(),pseudo:cells[0]||'Inconnu',key,type:cells[2]||'',assignedAt:parseOldDate(cells[3]),endsAt:parseOldDate(cells[4]),status:'active',discordId:'',email:'',notes:'Importé depuis l’ancien tableau HTML.'});added++}save();$('#html-report').textContent=`${added} attribution(s) ajoutée(s), ${skipped} ligne(s) déjà connue(s) ignorée(s).`;toast(`${added} attribution(s) importée(s).`)}
function download(name,type,content){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function exportAudit(){const q=v=>`"${String(v??'').replaceAll('"','""')}"`;const lines=['Statut;Pseudo Discord;ID Discord;E-mail;Clé;Type;Attribuée le;Échéance;Archivée le;Note'];for(const [status,items] of [['Active',db.assignments],['Archivée',db.archive]])for(const a of items)lines.push([status,a.pseudo,a.discordId,a.email,a.key,a.type,a.assignedAt,a.endsAt,a.archivedAt,a.notes].map(q).join(';'));download('keyledger-journal.csv','text/csv;charset=utf-8',`\uFEFF${lines.join('\r\n')}`)}
document.addEventListener('click',e=>{if(e.target.closest('[data-close-dialog]')){$('#assignment-dialog').close();return}if(e.target.closest('[data-close-note-dialog]')){$('#key-note-dialog').close();return}if(e.target.closest('[data-close-key-add-dialog]')){$('#key-add-dialog').close();return}if(e.target.closest('[data-close-login-dialog]')){$('#login-dialog').close();return}const v=e.target.closest('[data-view]')?.dataset.view;if(v)setView(v);const assign=e.target.closest('[data-assign]')?.dataset.assign;if(assign)openAssignment(assign);const edit=e.target.closest('[data-edit]')?.dataset.edit;if(edit)openAssignment('',edit);const archiveId=e.target.closest('[data-archive]')?.dataset.archive;if(archiveId)archive(archiveId);const releaseId=e.target.closest('[data-release-key]')?.dataset.releaseKey;if(releaseId)releaseKey(releaseId);const noteId=e.target.closest('[data-note-key]')?.dataset.noteKey;if(noteId)openKeyNote(noteId)});
$('#new-assignment').onclick=()=>openAssignment();$('#stock-search').oninput=renderStock;$('#assignment-search').oninput=renderAssignments;$('#history-search').oninput=renderHistory;$('#assignment-stock-key').onchange=updateKeyPreview;
$('#new-key').onclick=()=>{$('#key-value').value='';$('#key-type').value='';$('#key-source').value='';$('#key-add-note').value='';$('#key-add-dialog').showModal()};
$('#connection-button').onclick=async()=>{if(!cloud.configured){toast('Ajoute SUPABASE_ANON_KEY dans Netlify puis redéploie.');return}if(cloud.session){await cloud.client.auth.signOut();cloud.session=null;db=load();render();updateConnectionButton();toast('Déconnecté : retour au mode local.');return}$('#login-message').textContent='';$('#login-dialog').showModal()};
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();$('#login-message').textContent='Connexion…';try{const {data,error}=await cloud.client.auth.signInWithPassword({email:$('#login-email').value.trim(),password:$('#login-password').value});if(error)throw error;cloud.session=data.session;await refreshCloud();$('#login-dialog').close();updateConnectionButton();toast('Connecté : données Supabase synchronisées.')}catch(error){cloud.session=null;$('#login-message').textContent=error.message||'Connexion impossible.';updateConnectionButton()}});
$('#assignment-form').addEventListener('submit',async e=>{e.preventDefault();const editing=$('#assignment-id').value;const values={discordName:$('#client-pseudo').value.trim(),discordId:$('#discord-id').value.trim(),email:$('#client-email').value.trim(),assignedAt:$('#assignment-date').value,endsAt:$('#expiry-date').value,status:$('#assignment-status').value,notes:$('#assignment-notes').value.trim()};try{if(cloud.session){if(editing)await api('',{method:'PATCH',body:JSON.stringify({action:'update-assignment',assignmentId:editing,...values})});else await api('',{method:'POST',body:JSON.stringify({keyId:$('#assignment-stock-key').value,...values})});await refreshCloud();$('#assignment-dialog').close();toast(editing?'Attribution mise à jour.':'Clé attribuée et synchronisée.');return}let target;if(editing){target=db.assignments.find(a=>a.id===editing)}else{const stockId=$('#assignment-stock-key').value;const item=db.stock.find(k=>k.id===stockId&&k.state==='available');if(!item)return;item.state='assigned';target={id:uid(),key:item.key,type:item.type}}Object.assign(target,{pseudo:values.discordName,discordId:values.discordId,email:values.email,assignedAt:values.assignedAt,endsAt:values.endsAt,status:values.status,notes:values.notes});if(!editing)db.assignments.push(target);save();$('#assignment-dialog').close();toast(editing?'Attribution mise à jour.':'Clé attribuée : inventaire mis à jour.')}catch(error){toast(error.message)}});
$('#key-note-form').addEventListener('submit',async e=>{e.preventDefault();const key=db.stock.find(k=>k.id===$('#note-key-id').value);if(!key)return;try{if(cloud.session){await api('',{method:'PATCH',body:JSON.stringify({action:'note',keyId:key.id,note:$('#key-note').value.trim()})});await refreshCloud()}else{key.note=$('#key-note').value.trim();save()}$('#key-note-dialog').close();toast('Note de la clé enregistrée.')}catch(error){toast(error.message)}});
$('#key-add-form').addEventListener('submit',async e=>{e.preventDefault();const values={keyValue:$('#key-value').value.trim(),licenseType:canonicalType($('#key-type').value.trim()),sourceDate:$('#key-source').value.trim(),note:$('#key-add-note').value.trim()};if(!values.keyValue||!values.licenseType)return;try{if(cloud.session){await api('',{method:'PATCH',body:JSON.stringify({action:'add-key',...values})});await refreshCloud()}else{if(db.stock.some(k=>k.key===values.keyValue))throw new Error('Cette clé existe déjà.');db.stock.push({id:uid(),key:values.keyValue,type:values.licenseType,sourceDate:values.sourceDate,state:'available',note:values.note,importedAt:new Date().toISOString()});save()}$('#key-add-dialog').close();toast('Clé ajoutée au stock.')}catch(error){toast(error.message)}});
$('#csv-import').onchange=e=>e.target.files.length&&importCsv([...e.target.files]).catch(err=>toast(`Import impossible : ${err.message}`));$('#html-import').onchange=e=>e.target.files[0]&&importHtml(e.target.files[0]).catch(err=>toast(`Import impossible : ${err.message}`));
$('#export-json').onclick=()=>download(`keyledger-backup-${new Date().toISOString().slice(0,10)}.json`,'application/json',JSON.stringify(db,null,2));$('#export-audit').onclick=exportAudit;$('#restore-json').onchange=async e=>{try{const backup=JSON.parse(await e.target.files[0].text());if(![1,2].includes(backup?.version)||!Array.isArray(backup.stock)||!Array.isArray(backup.assignments))throw new Error('Format de sauvegarde invalide.');if(confirm('Remplacer toutes les données locales par cette sauvegarde ?')){db=backup;save();toast('Sauvegarde restaurée.')}}catch(err){toast(`Restauration impossible : ${err.message}`)}};
render();initCloud();
